baseURL: "http://blue-farid.ir"
publishDir: "docs"
languageCode: "en-us"
title: "Farid Masjedi"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

pagination:
  pagerSize: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Farid Masjedi"
  description: farid masjedi personal site!
  # staticPath: ""  # The path to serve the static files from
  favicon: "/blue-farid.webp"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    defaultTheme: "dark" # light

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Farid Masjedi" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hey, my name is"
    title: "Farid Masjedi."
    subtitle: "Crafting code and engineering software solutions is not just my job; It's my passion!"
    content: "dedicated Software Engineer with a zest for problem-solving and innovation, right here from the vibrant city of Tehran, Iran."
    image: "/profile.jpg"
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "/Resume.pdf"
      download: false
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/blue-farid
        - icon: fab fa-twitter
          url: https://twitter.com/blue__farid
        - icon: fab fa-telegram
          url: https://telegram.me/blue_farid
        - icon: fab fa-instagram
          url: https://instagram.com/blue.farid
        - icon: fab fa-linkedin
          url: https://linkedin.com/in/blue-farid
            # customIcons:
        # - icon: /fav.png
        # url: "https://blue-farid.ir"

  # About
  about:
    enable: true
    title: "About Me"
      #image: "/me.jpg"
    content: |-
      I'm Farid Masjedi, a passionate backend developer and software engineer, currently advancing the logistics and delivery ecosystem at [Snapp! Box](https://snapp-box.com) in Tehran. My academic journey in Computer Engineering unfolds at [Amirkabir University](https://aut.ac.ir). I excel in orchestrating complex projects, evidenced by my successful key contributions in Snapp! Box. Technically proficient in Java and OOP, I leverage frameworks like Spring and tools such as Docker to build robust solutions. 

    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Java"
        - "Spring Boot Framework"
        - "Docker"
        - "Kubernetes"
        - "Git"
        - "MySQL"
        - "Go"  
        - "C"
        - "Python"
        - "Maven"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Software Engineer"
        company: "Snapp Box"
        companyUrl: "https://snapp-box.com"
        date: "Nov 2022"
        content: "Snappbox is an on-demand urban delivery platform in Iran, offering businesses access to the country's largest delivery fleet, revolutionizing last-mile delivery with smart technology and operational excellence."        

        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        info:
          enable: true
          content: "I am currently working as a software engineer at Snapp! Box in Tehran, Iran."


      - job: "Back-end Developer"
        company: "Adanic"
        companyUrl: "https://adanic.ir"
        date: "Aug 2022 - Oct 2022"
        content:  "Adanic, founded in 2014, offers specialized banking solutions in Iran, with key infrastructure products and user-friendly applications. Serving notable clients like Ayandeh Bank and Parsian Bank, Adanic has quickly established itself as a go-to for technical financial expertise."
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: true
          content: "I worked as a back-end developer for 3 months in Adanic."

      - job: "Software Developer"
        company: "Informatic Services Corporation"
        companyUrl: "https://isc.co.ir"
        date: "Nov 2021 - Jul 2022"
        content: "ISC, established in December 1993, is the premier banking system provider for Iran's commercial banks and financial institutions. Headquartered in Tehran, ISC is the largest electronic banking operation in the Middle East, acclaimed for top rankings in technology and service categories. The company specializes in national banking infrastructure, core banking solutions, and offers robust support for over 8,000 branches and 7,000 VSAT terminals, ensuring secure and scalable financial transactions."
        info:
          enable: true
          content: "I worked as a software developer for 9 months in ISC."

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "BSC Computer Engineering"
        school:
          name: "Amirkabir University of Technology"
          url: "https://aut.ac.ir"
        date: "2020 - 2024"
          # GPA: ""
          # content: |-
          # Extracurricular Activities
          #  - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
          # - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.

  
  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
        image: /images/achievment.jpg
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
        image: /images/achievment.jpg
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
        image: /images/achievment.jpg
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Kardo!
        content: Led the development as an engineer manager of an online school platform in Iran, taking full responsibility for the project within a very small team. powered by https://gozar.team
        image: /kardoo-images/kardoo-1.png
        featured:
          name: Live!
          link: https://kardo.school
        badges:
          - "Django"
          - "Python"
          - "Vue.js"
  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
    email: blue.farid.masjedi@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      telegram: https://telegram.com  
        #facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
